-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- local cacher = require("vectorcode.config").get_cacher_backend()
-- vim.api.nvim_create_autocmd("LspAttach", {
--   callback = function()
--     local bufnr = vim.api.nvim_get_current_buf()
--     cacher.async_check(
--       "config",
--       vim.schedule_wrap(function()
--         cacher.register_buffer(bufnr, {
--           n_query = 10,
--         })
--       end),
--       nil
--     )
--   end,
--   desc = "Register buffer for VectorCode",
-- })
